---
title: "SNF_forsubjectsClustering_immune_proteomics"
author: ""
date: "2022/1/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Load library
```{r}
library(SNFtool)
library(ComplexHeatmap)
library(igraph)
library(tidygraph)
library(ggraph)
library(RColorBrewer)
library(readxl)
```

## Run SNF
```{r}
## First, set all the parameters:
K <- 20		# number of neighbors, usually (10~30)
alpha <- 0.5  	# hyperparameter, usually (0.3~0.8)
I <- 20 	# Number of Iterations, usually (10~20)
select_group <- "NC"

## Data import
meta_input <- read_excel("../input/中山100 sample meta list.xlsx")
meta_df <- data.frame(meta_input)
meta_df <- meta_df[!is.na(meta_df$Th1),]
colnames(meta_df) <- make.names(colnames(meta_df))
colnames(meta_df)[1] <- "sample"
immune_input <- meta_df[,c(1,14:95)]

protein_input <- read.csv("../input/ZS_100_sample_proteomics_QC_delete_50_percent_missing_knn_impute_log.csv")
protein_input$sample <- gsub("_FS", "", protein_input$sample)
protein_input$sample <- gsub("_", "-", protein_input$sample)

immune_df <- immune_input
protein_df <- protein_input[match(immune_df$sample, protein_input$sample),]

data1 <- immune_df[,-1]
data2 <- protein_df[,-1]
meta <- meta_df

## Normalize the data
Data1 <- standardNormalization(data1)
Data2 <- standardNormalization(data2)
rownames(Data1) <- rownames(Data2) <- immune_df$sample
## Calculate the pair-wise distance [squared Euclidean distances]
Dist1 <- SNFtool::dist2(as.matrix(Data1),as.matrix(Data1))
Dist2 <- SNFtool::dist2(as.matrix(Data2),as.matrix(Data2))

## next, construct similarity graphs, Computes affinity matrix from a generic distance matrix
W1 <- affinityMatrix(Dist1, K, alpha)
W2 <- affinityMatrix(Dist2, K, alpha)

## These similarity graphs have complementary information about clusters.
truelabel <- meta_df$disease

## then the overall matrix can be computed by similarity network fusion(SNF):
W = SNF(list(W1,W2), K, I)
```


## clustering on similarity matrix

### 2 clusters
```{r}
## With this unified graph W of size n x n, you can do either spectral clustering or Kernel NMF. If you need help with further clustering, please let us know. 
## for example, spectral clustering

C = 2					# number of clusters
group = spectralClustering(W, C) 	# the final subtypes information

## you can evaluate the goodness of the obtained clustering results by calculate Normalized mutual information (NMI): if NMI is close to 1, it indicates that the obtained clustering is very close to the "true" cluster information; if NMI is close to 0, it indicates the obtained clustering is not similar to the "true" cluster information.

displayClusters(W, group)
# SNFNMI = calNMI(group, truelabel)

## you can also find the concordance between each individual network and the fused network

ConcordanceMatrix = concordanceNetworkNMI(list(W, W1,W2), C)
# displayClustersWithHeatmap(W, group)

res <- data.frame(sample = colnames(W),
                  snf_cluster = group)
openxlsx::write.xlsx(res, file = paste0("SNF_", C, "clusters.xlsx"), overwrite = T)
```

#### Visualization
```{r}
# ht_col <- colorRamp2(c(0, 0.1, 0.3), c("green", "white", "red"))
pal_cols <- c("#7c7f81","#1ba1e2","#008a00","#ffac30", "#e51400")
cluster_col <- brewer.pal(n = 3, 
                          name = "Dark2")[1:2]
names(cluster_col) <- unique(group)
ha = HeatmapAnnotation(
                       clusters = as.factor(group[order(group)]),
                       col = list(
                                  clusters = cluster_col))

w_df <- W[order(group), order(group)]
diag(w_df) <- NA

ht_all <- Heatmap(w_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_all
pdf(paste0("SNF_", C, "clusters_similarity_heatmap.pdf"), width = 8, height = 6)
ht_all
dev.off()

w1_df <- W1[order(group), order(group)]
diag(w1_df) <- NA
ht_w1 <- Heatmap(w1_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w1
pdf(paste0("SNF_", C, "clusters_similarity_immune_heatmap.pdf"), width = 8, height = 6)
ht_w1
dev.off()


w2_df <- W2[order(group), order(group)]
diag(w2_df) <- NA
ht_w2 <- Heatmap(w2_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w2
pdf(paste0("SNF_", C, "clusters_similarity_protein_heatmap.pdf"), width = 8, height = 6)
ht_w2
dev.off()
```

#### Network plot
```{r}
g <- graph_from_adjacency_matrix(W, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W1, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W1),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_immune_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W2, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W2),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_protein_networkplot.pdf"), width = 6, height = 4)
```



### 3 clusters
```{r}
## With this unified graph W of size n x n, you can do either spectral clustering or Kernel NMF. If you need help with further clustering, please let us know. 
## for example, spectral clustering

C = 3					# number of clusters
group = spectralClustering(W, C) 	# the final subtypes information

## you can evaluate the goodness of the obtained clustering results by calculate Normalized mutual information (NMI): if NMI is close to 1, it indicates that the obtained clustering is very close to the "true" cluster information; if NMI is close to 0, it indicates the obtained clustering is not similar to the "true" cluster information.

displayClusters(W, group)
SNFNMI = calNMI(group, truelabel)

## you can also find the concordance between each individual network and the fused network

ConcordanceMatrix = concordanceNetworkNMI(list(W, W1,W2), C)
# displayClustersWithHeatmap(W, group)
res <- data.frame(sample = colnames(W),
                  snf_cluster = group)
openxlsx::write.xlsx(res, file = paste0("SNF_", C, "clusters.xlsx"), overwrite = T)
```

#### Visualization
```{r}
# ht_col <- colorRamp2(c(0, 0.1, 0.3), c("green", "white", "red"))
pal_cols <- c("#7c7f81","#1ba1e2","#008a00","#ffac30", "#e51400")
cluster_col <- brewer.pal(n = 4, 
                          name = "Dark2")[1:C]
names(cluster_col) <- unique(group)
ha = HeatmapAnnotation(
                       clusters = as.factor(group[order(group)]),
                       col = list(
                                  clusters = cluster_col))

w_df <- W[order(group), order(group)]
diag(w_df) <- NA

ht_all <- Heatmap(w_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_all
pdf(paste0("SNF_", C, "clusters_similarity_heatmap.pdf"), width = 8, height = 6)
ht_all
dev.off()

w1_df <- W1[order(group), order(group)]
diag(w1_df) <- NA
ht_w1 <- Heatmap(w1_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w1
pdf(paste0("SNF_", C, "clusters_similarity_immune_heatmap.pdf"), width = 8, height = 6)
ht_w1
dev.off()


w2_df <- W2[order(group), order(group)]
diag(w2_df) <- NA
ht_w2 <- Heatmap(w2_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w2
pdf(paste0("SNF_", C, "clusters_similarity_protein_heatmap.pdf"), width = 8, height = 6)
ht_w2
dev.off()
```

#### Network plot
```{r}
g <- graph_from_adjacency_matrix(W, weighted=TRUE)
graph_df <- as_data_frame(g)
graph_df$weight[graph_df$weight <= 0.005] <- 0
node_df <- data.frame(name = colnames(W),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W1, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W1),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_immune_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W2, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W2),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_protein_networkplot.pdf"), width = 6, height = 4)
```




### 4 clusters
```{r}
## With this unified graph W of size n x n, you can do either spectral clustering or Kernel NMF. If you need help with further clustering, please let us know. 
## for example, spectral clustering

C = 4					# number of clusters
group = spectralClustering(W, C) 	# the final subtypes information

## you can evaluate the goodness of the obtained clustering results by calculate Normalized mutual information (NMI): if NMI is close to 1, it indicates that the obtained clustering is very close to the "true" cluster information; if NMI is close to 0, it indicates the obtained clustering is not similar to the "true" cluster information.

displayClusters(W, group)
SNFNMI = calNMI(group, truelabel)

## you can also find the concordance between each individual network and the fused network

ConcordanceMatrix = concordanceNetworkNMI(list(W, W1,W2), C)
# displayClustersWithHeatmap(W, group)
res <- data.frame(sample = colnames(W),
                  snf_cluster = group)
openxlsx::write.xlsx(res, file = paste0("SNF_", C, "clusters.xlsx"), overwrite = T)
```

#### Visualization
```{r}
# ht_col <- colorRamp2(c(0, 0.1, 0.3), c("green", "white", "red"))
pal_cols <- c("#7c7f81","#1ba1e2","#008a00","#ffac30", "#e51400")
cluster_col <- brewer.pal(n = 4, 
                          name = "Dark2")[1:C]
names(cluster_col) <- unique(group)
ha = HeatmapAnnotation(
                       clusters = as.factor(group[order(group)]),
                       col = list(
                                  clusters = cluster_col))

w_df <- W[order(group), order(group)]
diag(w_df) <- NA

ht_all <- Heatmap(w_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_all
pdf(paste0("SNF_", C, "clusters_similarity_heatmap.pdf"), width = 8, height = 6)
ht_all
dev.off()

w1_df <- W1[order(group), order(group)]
diag(w1_df) <- NA
ht_w1 <- Heatmap(w1_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w1
pdf(paste0("SNF_", C, "clusters_similarity_immune_heatmap.pdf"), width = 8, height = 6)
ht_w1
dev.off()


w2_df <- W2[order(group), order(group)]
diag(w2_df) <- NA
ht_w2 <- Heatmap(w2_df,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4),
        show_row_dend = F,
        show_column_dend = F,
        heatmap_legend_param = list(title = "similarity"),
        top_annotation = ha)
ht_w2
pdf(paste0("SNF_", C, "clusters_similarity_protein_heatmap.pdf"), width = 8, height = 6)
ht_w2
dev.off()
```

#### Network plot
```{r}
g <- graph_from_adjacency_matrix(W, weighted=TRUE)
graph_df <- as_data_frame(g)
graph_df$weight[graph_df$weight <= 0.005] <- 0
node_df <- data.frame(name = colnames(W),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W1, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W1),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_immune_networkplot.pdf"), width = 6, height = 4)
```

```{r}
g <- graph_from_adjacency_matrix(W2, weighted=TRUE)
graph_df <- as_data_frame(g)
node_df <- data.frame(name = colnames(W2),
                      cluster = group)
node_df$cluster <- as.factor(node_df$cluster)

mygraph <- as_tbl_graph(graph_df, directed = F)

mygraph <- mygraph %>%
  activate(nodes) %>%
  left_join(node_df, by = "name") %>%
  dplyr::rename(label = name)

g_nodes <- activate(mygraph, nodes) %>% data.frame()

nodes_col <- brewer.pal(n = 8, name = "Set1")[1:C]
set.seed(123)
ggraph(mygraph, layout = "fr") + 
  geom_edge_link(color = "grey", alpha = 0.1) + 
  geom_node_point(aes(colour = cluster), size = 4) +
  scale_colour_manual(values = cluster_col) +
  theme_graph(base_family="sans")
ggsave(paste0("SNF_", C, "clusters_protein_networkplot.pdf"), width = 6, height = 4)
```

## plotAlluvial
```{r}
pdf("SNF_kselect_alluvialplot.pdf", width = 7, height = 5)
plotAlluvial(W, 2:5, color.vect = "red")
dev.off()
```




