---
title: "Data analysis"
author: ""
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: true
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    use_bookdown: false
    highlight: haddock
---

## Load library
```{r load packages, results='hide', message=F, warning=F,include=F}
rm(list=ls())
library(phyloseq)
library(microbiome)
library(tibble)
library(dplyr)
library(vegan)
library(flextable)
library(ggpubr)
library(gginnards)
library(patchwork)
library(microbiomeMarker)
library(ComplexHeatmap)
library(pheatmap)
```



```{r set color , include=F}
# color set
mycols <<- c(
  "#3cb44b", "#4363d8", "#e6194b",
  "#911eb4", "#46f0f0", "#f032e6", "#bcf60c", "#fabebe",
  "#008080", "#e6beff", "#9a6324", "#fffac8", "#800000",
  "#aaffc3", "#808000", "#ffd8b1", "#000075", "#808080",
  "#000000"
)

```

## Function
```{r echo=F, results='hide', message=F, warning=F,include=F}
# some function
convertSeq2ASV<-function(phy){
  # rename sequence to ASV
  
  if(taxa_are_rows(phy) == F){
    phy <- t(phy)
    print("Converted to taxa name are rows")
  }
  
  if(all(rownames(otu_table(phy)) ==rownames(tax_table(phy)))){ #check names 
    out <- cbind(paste0("ASV",seq(1:nrow(otu_table(phy)))),rownames(tax_table(phy)),tax_table(phy))
    write.csv(out,file=paste0("../data/ref_table_seq2asv_",Sys.Date(),".csv"),row.names = T,quote = F)
    taxa_names(phy) <- paste0("ASV",seq(1:nrow(otu_table(phy))))
  }else{
    message("rownames in otu table is not equal to rownames in tax table")
  }
  return(phy)
}
```

## Import phyloseq

```{r load data, message=F, warning=F,include=T}
ps.mice <- readRDS("../data_processing/gmu_16S_phyloseq_59samples.rds")
print(ps.mice) # 3570 taxa and 59 samples

phy <- ps.mice
```

## Data prcessing
```{r}
# processing raw data as needed

phy_core <- core(phy, detection = 5, prevalence = .2) # change parameter if needed
print(phy_core) # 740 taxa and 59 samples
```


## Differential by lefse
```{r , include=F}
plot_res <- function(input_tab,ref,input_col,dpi=300,width=5,height=5,ysize=5,lsize=5,outname,device=device){
  
 for (i in 1:nrow(input_tab)){
    if( input_tab$enrich_group[i] == ref){
      input_tab$ef_lda[i] <- -1*input_tab$ef_lda[i]
    }
  }

  
  p1 <- ggbarplot(input_tab %>% data.frame(), x = "feature", y = "ef_lda",
          fill = "enrich_group",           
          color = "white",            
          palette = input_col,           
          sort.val = "desc",         
          sort.by.groups = FALSE,     
          x.text.angle = 90,          
          ylab = "LDA score (log10)",
          rotate = TRUE,
          ggtheme = theme_pubr(),
          width=0.9
          ) +
    theme(axis.text.y=element_text(size=ysize),
          axis.text.x=element_text(size=ysize),
          axis.title.y = element_blank())+
    theme(legend.text=element_text(size=lsize))+
    theme(axis.text.y=element_text(size=lsize),
          legend.text=element_text(size=lsize),
          axis.title.x=element_text(size=lsize),
          legend.title = element_text(size = lsize) )
  ggsave(p1,filename = outname,device = device,dpi = dpi,width = width,height = height)
  }

```

### ASV level
```{r}
dir.create("figures")
dir.create("tables")
phy_normal <- microbiomeMarker::normalize(phy_core,method="CPM")
sample_data(phy_normal)$Groups <- gsub(" \\+ ","-",sample_data(phy_normal)$Groups)
sample_data(phy_normal)$Groups <- factor(sample_data(phy_normal)$Groups,levels = c("Control","Model","Model_AC","Model_AC_GV971L","Model_AC_GV971H"))


allcomb <- combn(levels(sample_data(phy_normal)$Groups),m = 2)
colcomb <- combn(1:5,m=2)

for (i in 1:ncol(allcomb)){
  sig_taxa <- c()
  phy_tmp <- subset_samples(phy_normal,Groups %in% c(allcomb[,i]))
  print(phy_tmp) # 740 taxa and 24 samples
  
  mm_asv <- run_lefse(phy_tmp,
      wilcoxon_cutoff = 0.05,
      norm = "none",
      group = "Groups",
      kw_cutoff = 0.05,
      multigrp_strat = TRUE,
      lda_cutoff = 2,
      taxa_rank = "none"
  )
  
  out_tab <- mm_asv@marker_table
  out_tab$feature <- out_tab$feature
  
  sig_taxa <- c(sig_taxa,out_tab$feature)
  out_tab$feature  <-  apply(cbind(phy_tmp@tax_table[out_tab$feature ,c(4,5)] ,out_tab$feature ),1,function(x){
    paste0(x,collapse = "|")
  })
  
  write.csv(out_tab,file = paste0("tables/lefse_barplot_Groups_",allcomb[,i][1],"_vs_",allcomb[,i][2],"_cutoff2_p0.05_ASV.csv"))

  # if (dim(out_tab)[1]<=5 ){
  #   height <- 2
  # } else if (dim(out_tab)[1] < 12) {
  #   height <- 4  
  # } else{ 
  #   height <- dim(out_tab)[1]/6
  # }  
  if (dim(out_tab)[1]<=5 ){
    height <- 2
  } else if (dim(out_tab)[1] < 12) {
    height <- 4
  } else{ 
    height <- 3 + dim(out_tab)[1]/6
  }  

  plot_res(input_tab = out_tab,ref = allcomb[,i][1],device = "pdf",width = 12,height=height,input_col = mycols[colcomb[,i]],ysize = 10,lsize=10,outname = paste0("figures/lefse_barplot_Groups_",allcomb[,i][1],"_vs_",allcomb[,i][2],"_cutoff2_p0.05_ASV.pdf"))
  
  ##### Cladogram

  mm_all <- run_lefse(phy_tmp,
      wilcoxon_cutoff = 0.05,
      norm = "none",
      group = "Groups",
      kw_cutoff = 0.05,
      multigrp_strat = TRUE,
      lda_cutoff = 2,
      taxa_rank = "all"

  )

  if(length(unique(mm_all@marker_table$enrich_group)) == 2) {
    mycol <- mycols[colcomb[,i]]
  }else if(length(unique(mm_all@marker_table$enrich_group)) == 1) {
    if(unique(mm_all@marker_table$enrich_group) == allcomb[,i][1]){
      mycol <- mycols[colcomb[,i][1]]
    }else if(unique(mm_all@marker_table$enrich_group) == allcomb[,i][2]) {
      mycol <- mycols[colcomb[,i][2]]
    }
  }

  plot_cladogram(mm_all, only_marker = T,color = mycol,marker_legend_param = list(title.position = "top", label.position = "right",ncol=3)) +
      theme(plot.margin = margin(0, 0, 0, 0)) + theme(legend.position = "right")
  ggsave(paste0("figures/lefse_cladogram_Groups_",allcomb[,i][1],"_vs_",allcomb[,i][2],"_cutoff2_p0.05_ASV.pdf"),width = 30,height = 20)
}
```



### Genus level
```{r}
dir.create("figures")
dir.create("tables")
phy_normal <- microbiomeMarker::normalize(phy_core,method="CPM")
sample_data(phy_normal)$Groups <- gsub(" \\+ ","-",sample_data(phy_normal)$Groups)
sample_data(phy_normal)$Groups <- factor(sample_data(phy_normal)$Groups,levels = c("Control","Model","Model_AC","Model_AC_GV971L","Model_AC_GV971H"))

allcomb <- combn(levels(sample_data(phy_normal)$Groups),m = 2)
colcomb <- combn(1:5,m=2)

for (i in 1:ncol(allcomb)){
  sig_taxa <- c()
  phy_tmp <- subset_samples(phy_normal,Groups %in% c(allcomb[,i]))
  print(phy_tmp) # 740 taxa and 24 samples
  
  mm_Genus <- run_lefse(phy_tmp,
    wilcoxon_cutoff = 0.05,
    norm = "none",
    group = "Groups",
    kw_cutoff = 0.05,
    multigrp_strat = TRUE,
    lda_cutoff = 2,
    taxa_rank = "Genus"
  )
  
  out_tab <- mm_Genus@marker_table
  out_tab$feature <- out_tab$feature
  
  sig_taxa <- c(sig_taxa,out_tab$feature)
  out_tab$feature  <-  gsub("_g__","_g__NA",out_tab$feature)

  # out_tab$feature  <-  apply(cbind(phy_tmp@tax_table[out_tab$feature ,c(4,5)] ,out_tab$feature ),1,function(x){
  #   paste0(x,collapse = "|")
  # })
  # 
  write.csv(out_tab,file = paste0("tables/lefse_barplot_Groups_",allcomb[,i][1],"_vs_",allcomb[,i][2],"_cutoff2_p0.05_Genus.csv"))

  if (dim(out_tab)[1]<=5 ){
    height <- 2
  } else if (dim(out_tab)[1] < 12) {
    height <- 4
  } else{ 
    height <- 3+dim(out_tab)[1]/6
  }  

  plot_res(input_tab = out_tab,ref = allcomb[,i][1],device = "pdf",width = 12,height=height,input_col = mycols[colcomb[,i]],ysize = 10,lsize=10,outname = paste0("figures/lefse_barplot_Groups_",allcomb[,i][1],"_vs_",allcomb[,i][2],"_cutoff2_p0.05_Genus.pdf"))
  
}
```


